apiVersion: apps/v1
kind: Deployment
metadata:
  name: pond-web
  labels:
    app: pond-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pond-web
  template:
    metadata:
      labels:
        app: pond-web
    spec:
      containers:
      - name: pond-web
        image: pond-web:${VERSION}
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: GRPC_HOST
          value: "pond-server"
        - name: GRPC_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: pond-web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: pond-web 